### ISSUE TITLE
'Name' object is not iterable

### ISSUE THREAD

**Issue by mandshaw** [alex-sherman/deco#22]
Hey,

I am looking at deco and thought would be cool to use.

What I am doing is I have a parent thread who creates a csv writes headers to the file and then spawns child threads to go to a rest api and request data until there is no more data to request. At which point they return a list of results and the parent thread takes the results and writes them after the header

I keep hitting the same error. The error is a bit meaningless and there are no comments in the code so I cant make head or tails of what is going on?

Any thoughts?

Stack below:

Error
Traceback (most recent call last):
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\unittest2\case.py", line 67, in testPartExecutor
    yield
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\unittest2\case.py", line 625, in run
    testMethod()
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\freezegun\api.py", line 451, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "D:\Projects\Python\dbexport\tests\test_dbexport.py", line 95, in test_something
    export(database, output_dir=actual_dir)
  File "D:\Projects\Python\dbexport\dbexport\dbexport.py", line 53, in export
    export_dbrw(db_details, start_time, end_time, target_directory)
  File "D:\Projects\Python\dbexport\dbexport\dbrw_export.py", line 129, in export_dbrw
    run_dbrw_query(query.get('query_name'), bindings, write_headers, (csvwriter,), append_records, (csvwriter,))
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\conc.py", line 47, in __call__
    rewriter.visit(node.body[0])
  File "C:\Python27\Lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\astutil.py", line 85, in visit_FunctionDef
    self.generic_visit(node)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\astutil.py", line 55, in generic_visit
    super(NodeTransformer, self).generic_visit(node)
  File "C:\Python27\Lib\ast.py", line 249, in generic_visit
    self.visit(item)
  File "C:\Python27\Lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\astutil.py", line 55, in generic_visit
    super(NodeTransformer, self).generic_visit(node)
  File "C:\Python27\Lib\ast.py", line 249, in generic_visit
    self.visit(item)
  File "C:\Python27\Lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\astutil.py", line 55, in generic_visit
    super(NodeTransformer, self).generic_visit(node)
  File "C:\Python27\Lib\ast.py", line 251, in generic_visit
    self.visit(value)
  File "C:\Python27\Lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\astutil.py", line 55, in generic_visit
    super(NodeTransformer, self).generic_visit(node)
  File "C:\Python27\Lib\ast.py", line 251, in generic_visit
    self.visit(value)
  File "C:\Python27\Lib\ast.py", line 241, in visit
    return visitor(node)
  File "C:\Users\an.other\Envs\deco-bug\lib\site-packages\deco\astutil.py", line 57, in generic_visit
    returns = [i for i, child in enumerate(node.body) if type(child) is ast.Return]
TypeError: 'Name' object is not iterable

Cheers, Nice piece of kit (When I did get it to work)

**Comment by alex-sherman** [comment]
Thanks for finding this! I didn't realize, but there are several items in the Python AST that have `body` fields which contain a single element rather than a list. I'll update deco today at some point probably. If possible, could you post a little snippet of your `@synchronized` function so that I can make sure my solution works?

**Comment by mandshaw** [comment]
No Worries,

I am was looking to use it to refactor old code to be parallel. Unfortunately the code is sensitive and I cant share it. Let me see if I can reproduce dummy code that throws the same error

**Comment by alex-sherman** [comment]
OK don't worry about sharing it then, could you let me know if your synchronized function contains any of the following:

- exec statements or calls
- lambda expressions
- if else expressions like: a if b else c

**Comment by mandshaw** [comment]
Yes,

I have some calls to other functions in the sync (that aren't decorated to be concurrent) they are called before a for loop. The for loop then loops for my thread count and calls the concurrent function

concurrent functions are all consuming data from a REST API. When there is no more data to retrieve the concurrent function returns a None. In my sync function i then have to check the returned result from the function (I don't want to add a None to my collection of results for example). So I have a if to do a "if result is not None:"

I have some ifs right at the top of my sync function as well which check arguments

My params to my conc function are a int and a string

Hope this helps

**Comment by alex-sherman** [comment]
I've just pushed b357087be7bd1f767fcc40610df216dee2a9559e which I think should fix your issue. Please let me know if it doesn't, otherwise feel free to close this issue.

Thanks again for pointing this out!
