### ISSUE TITLE
ValueError: If using all scalar values, you must pass an index  

### ISSUE THREAD

**Issue by aliabbasjp** [alex-sherman/deco#42]
getting following error:

```
@concurrent
def createtraindata(filpath):
    print filpath

@synchronized
def iterate(fils):
    test={}
    for f in fils:
        test[f[0]]=createtraindata(f[0])
    return test


Traceback (most recent call last):                                                                                                                                                     
  File "createdata.py", line 183, in <module>                                                                                                                                          
    print iterate(fils)                                                                                                                                                                
  File "/home/ttt/anaconda2/lib/python2.7/site-packages/deco/conc.py", line 58, in __call__                                                                                       
    return self.f(*args, **kwargs)                                                                                                                                                     
  File "<string>", line 257, in iterate                                                                                                                                                
  File "/home/ttt/anaconda2/lib/python2.7/site-packages/deco/conc.py", line 129, in wait                                                                                          
    results.append(self.results.pop().get())                                                                                                                                           
  File "/home/ttt/anaconda2/lib/python2.7/site-packages/deco/conc.py", line 144, in get                                                                                           
    result, operations = self.async_result.get()                                                                                                                                       
  File "/home/ttt/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get                                                                                              
    raise self._value                                                                                                                                                                  
ValueError: If using all scalar values, you must pass an index  
```

**Comment by alex-sherman** [comment]
I think the error is coming from Pandas, can you include what is getting passed into `fils`?

**Comment by aliabbasjp** [comment]
thanks resolved
