### ISSUE TITLE
conc_test.py was eror in my python 3

### ISSUE THREAD

**Issue by sukmabadar** [alex-sherman/deco#51]
here i was run conc_test.py 

$ python conc_test.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/synchronize.py", line 29, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conc_test.py", line 29, in <module>
    test_size(SIZE)
  File "/storage/emulated/0/Download/termuxData/deco/deco/conc.py", line 61, in __call__
    return self.f(*args, **kwargs)
  File "<string>", line 5, in test_size
  File "/storage/emulated/0/Download/termuxData/deco/deco/conc.py", line 110, in assign
    self.assigns.append((target, self(*args, **kwargs)))
  File "/storage/emulated/0/Download/termuxData/deco/deco/conc.py", line 121, in __call__
    self.concurrency = self.conc_constructor(*self.conc_args, **self.conc_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
    self._setup_queues()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/pool.py", line 249, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/synchronize.py", line 34, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

what i forgoted to modul install?

**Comment by alex-sherman** [comment]
The error seems to be an issue with your Python installation, but I'm not sure beyond that.
