### ISSUE TITLE
"posonlyargs" missing from arguments

### ISSUE THREAD

**Issue by RashiqAzhan** [alex-sherman/deco#64]
I am getting this error but I'm not sure what I did wrong.
[I've got this](https://stackoverflow.com/questions/59564990/typeerror-required-field-posonlyargs-missing-from-arguments-error-running-a-p) but this was fixed on python version 3.8.1. I'm using 3.8.8.

Offending Code:
```python
@concurrent.threaded(processes=10240)
def extraction_xor(pixel, message_length):
    # Separate the pixel colors
    red = pixel[0]
    green = pixel[1]
    blue = pixel[2]

    # Convert pixel colors to an array before being represented in binary
    red_binary = np.unpackbits(np.array(red))
    green_binary = np.unpackbits(np.array(green))
    blue_binary = np.unpackbits(np.array(blue))

    # XOR the bits to extract the message
    message_bit_from_red = message_bit_from_green = message_bit_from_blue = ''
    if message_length >= 1:
        message_bit_from_red = str(red_binary[-2] ^ red_binary[-1])
    if message_length >= 2:
        message_bit_from_green = str(green_binary[-2] ^ green_binary[-1])
    if message_length >= 3:
        message_bit_from_blue = str(blue_binary[-2] ^ blue_binary[-1])

    return [message_bit_from_red, message_bit_from_green, message_bit_from_blue]

@synchronized
def extract_from_stego_pixel(pixel_array, message_length):
    message = []
    # Get pixel rows
    for x in range(pixel_array.shape[0]):
        # Get pixel columns
        for y in range(pixel_array.shape[1]):
            message.append(extraction_xor(pixel_array[x][y], message_length))
            message_length -= 3
            if (message_length <= 0):
                break
        if (message_length <= 0):
            break

    return message
```

Terminal output:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "...\JetBrains\Toolbox\apps\PyCharm-P\ch-1\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "...\JetBrains\Toolbox\apps\PyCharm-P\ch-1\203.7148.72\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../data_embedding.py", line 302, in <module>
    main()
  File ".../data_embedding.py", line 248, in main
    message_in_3bit_groups = extract_from_stego_pixel(second_pixel_array, 40)
  File "...\.venv\lib\site-packages\deco\conc.py", line 58, in __call__
    out = compile(self.ast, "<string>", "exec")
TypeError: required field "posonlyargs" missing from arguments
```

**Comment by alex-sherman** [comment]
Thanks for finding this! I think I've fixed it in 7ae482f0440e4440f758a34a160a134feb888d18, lemme know if that doesn't work.

**Comment by RashiqAzhan** [comment]
Welcome but the Thanks belong to you. So, Thank you for your work.

How do I get this fix? I haven't found any updates to the Pip. Sorry if the question is dumb.

**Comment by alex-sherman** [comment]
No that's my bad, I just now made a new release 0.6.1.

It is also possible to install libraries from source by just downloading them and running `python setup.py install` (if the include a setup.py).
